name: Update URLS
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  updateURLS:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ide
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Checkout ide-urls
        uses: actions/checkout@v3
        with:
          repository: devonfw/ide-urls
          path: ide-urls
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'
      - name: Build and run url updater
        run: |
          cd ide
          mvn -B -ntp -Dstyle.color=always install
          mvn -B -ntp -Dstyle.color=always exec:java -Dexec.mainClass="com.devonfw.tools.ide.url.UpdateInitiator" -Dexec.args="../ide-urls PT5H30M"
      - name: Commit and push to ide-urls
        run: |
          cd ide-urls
          git config --global user.name ${{ secrets.BUILD_USER }}
          git config --global user.email ${{ secrets.BUILD_USER_EMAIL }}
          if [ "$(git status -z)" = "" ]
          then
            echo "No changes, nothing to commit."
          else
            git add .
            git commit -m "Update urls"
            git push
          fi
