name: Update URLS
on:
  push

jobs:
  updateURLS:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ide
        uses: actions/checkout@v3
      - name: Checkout ide-urls
        uses: actions/checkout@v3
        with:
          repository: devonfw/ide-urls
          path: ide-urls
          token: ${{ secrets.ACTION_PUSH_TOKEN }}
      - name: Build and run url updater
        run: |
          cd url-updater
          mvn install
          mvn exec:java -Dexec.mainClass="com.devonfw.tools.ide.url.UpdateInitiator" -Dexec.args="../ide-urls"
      - name: Commit and push to ide-urls
        run: |
          cd ide-urls
          git add .
          git config --global user.name ${{ secrets.BUILD_USER }}
          git config --global user.email ${{ secrets.BUILD_USER_EMAIL }}
          git commit -m "Update urls"
          git push
